# Generated by Django 5.0.4 on 2024-04-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='production_companies',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='production_countries',
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(null=True),
        ),
    ]
