# Generated by Django 5.0.4 on 2024-04-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggest', '0005_delete_dataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
